// this file is auto-generated by the manager, please do not modify
import '../deps/https:__ajax.googleapis.com_ajax_libs_jquery_3.1.1_jquery.min.js';
import '../deps/https:__ajax.googleapis.com_ajax_libs_jqueryui_1.12.1_jquery-ui.min.js';
import '../deps/https:__code.jquery.com_ui_1.13.2_themes_base_jquery-ui.css';
import '../deps/https:__cdn.jsdelivr.net_npm_@popperjs_core@2.11.8_dist_umd_popper.min.js';
