// this file was generated by a script, please do not modify it. if you see any problems, please raise an issue on https://github.com/tsaxking/webpack-template/issues

import { accounts } from './tables.ts';
import { members } from './tables.ts';
import { roles } from './tables.ts';
import { account_roles } from './tables.ts';
import { permissions } from './tables.ts';
import { version } from './tables.ts';
import { sessions } from './tables.ts';
import { account_settings } from './tables.ts';
import { select_permissions_all } from './tables.ts';
import { select_roles_from_name } from './tables.ts';
import { delete_roles_delete } from './tables.ts';
import { update_roles_update } from './tables.ts';
import { insert_roles_new } from './tables.ts';
import { select_roles_from_id } from './tables.ts';
import { select_roles_all } from './tables.ts';
import { delete_sessions_delete } from './tables.ts';
import { delete_sessions_delete_all } from './tables.ts';
import { update_sessions_update } from './tables.ts';
import { insert_sessions_new } from './tables.ts';
import { select_sessions_get } from './tables.ts';
import { select_sessions_all } from './tables.ts';
import { delete_member_delete } from './tables.ts';
import { update_member_update_title } from './tables.ts';
import { update_member_update_status } from './tables.ts';
import { update_member_update_resume } from './tables.ts';
import { update_member_remove_from_board } from './tables.ts';
import { insert_member_new } from './tables.ts';
import { update_member_update_bio } from './tables.ts';
import { update_member_add_to_board } from './tables.ts';
import { select_member_all } from './tables.ts';
import { update_account_unverify } from './tables.ts';
import { update_account_set_verification } from './tables.ts';
import { delete_account_delete } from './tables.ts';
import { select_account_unverified } from './tables.ts';
import { update_account_change_password } from './tables.ts';
import { insert_account_save_settings } from './tables.ts';
import { select_account_from_username } from './tables.ts';
import { update_account_update_picture } from './tables.ts';
import { select_account_from_verification_key } from './tables.ts';
import { select_account_verified } from './tables.ts';
import { update_account_verify } from './tables.ts';
import { select_account_get_settings } from './tables.ts';
import { update_account_change_email } from './tables.ts';
import { delete_account_remove_role } from './tables.ts';
import { insert_account_add_role } from './tables.ts';
import { select_account_from_email } from './tables.ts';
import { insert_account_new } from './tables.ts';
import { update_account_request_password_change } from './tables.ts';
import { select_account_from_password_change } from './tables.ts';
import { select_account_from_id } from './tables.ts';
import { select_account_all } from './tables.ts';
import { update_account_request_email_change } from './tables.ts';
import { update_account_change_username } from './tables.ts';
import { select_db_get_version } from './tables.ts';
import { update_db_change_version } from './tables.ts';
import { insert_db_init } from './tables.ts';

export type queries = {
    'permissions/all': [[select_permissions_all], permissions];

    'permissions/from-role': [
        [
            {
                role_id: string;
            },
        ],
        permissions,
    ];

    'permissions/remove-from-role': [
        [
            {
                role_id: string;
                permission: string;
            },
        ],
        unknown,
    ];

    'permissions/add-to-role': [
        [
            {
                role_id: string;
                permission: string;
            },
        ],
        unknown,
    ];

    'roles/from-name': [[select_roles_from_name], roles];

    'roles/delete': [[delete_roles_delete], unknown];

    'roles/update': [[update_roles_update], unknown];

    'roles/new': [[insert_roles_new], unknown];

    'roles/from-id': [[select_roles_from_id], roles];

    'roles/all': [[select_roles_all], roles];

    'roles/from-username': [
        [
            {
                username: string;
            },
        ],
        roles,
    ];

    'sessions/delete': [[delete_sessions_delete], unknown];

    'sessions/delete-all': [[delete_sessions_delete_all], unknown];

    'sessions/update': [[update_sessions_update], unknown];

    'sessions/new': [[insert_sessions_new], unknown];

    'sessions/get': [[select_sessions_get], sessions];

    'sessions/all': [[select_sessions_all], sessions];

    'sessions/sign-in': [
        [
            {
                id: string;
                account_id: string;
            },
        ],
        unknown,
    ];

    'sessions/sign-out': [
        [
            {
                id: string;
            },
        ],
        unknown,
    ];

    'member/delete': [[delete_member_delete], unknown];

    'member/update-title': [[update_member_update_title], unknown];

    'member/update-status': [[update_member_update_status], unknown];

    'member/update-resume': [[update_member_update_resume], unknown];

    'member/remove-from-board': [[update_member_remove_from_board], unknown];

    'member/new': [[insert_member_new], unknown];

    'member/update-bio': [[update_member_update_bio], unknown];

    'member/add-to-board': [[update_member_add_to_board], unknown];

    'member/all': [[select_member_all], members];

    'member/from-username': [
        [
            {
                username: string;
            },
        ],
        members,
    ];

    'account/unverify': [[update_account_unverify], unknown];

    'account/set-verification': [[update_account_set_verification], unknown];

    'account/delete': [[delete_account_delete], unknown];

    'account/unverified': [[select_account_unverified], accounts];

    'account/change-password': [[update_account_change_password], unknown];

    'account/save-settings': [[insert_account_save_settings], unknown];

    'account/from-username': [[select_account_from_username], accounts];

    'account/update-picture': [[update_account_update_picture], unknown];

    'account/from-verification-key': [
        [select_account_from_verification_key],
        accounts,
    ];

    'account/verified': [[select_account_verified], accounts];

    'account/verify': [[update_account_verify], unknown];

    'account/get-settings': [[select_account_get_settings], account_settings];

    'account/change-email': [[update_account_change_email], unknown];

    'account/remove-role': [[delete_account_remove_role], unknown];

    'account/add-role': [[insert_account_add_role], unknown];

    'account/from-email': [[select_account_from_email], accounts];

    'account/new': [[insert_account_new], unknown];

    'account/request-password-change': [
        [update_account_request_password_change],
        unknown,
    ];

    'account/from-password-change': [
        [select_account_from_password_change],
        accounts,
    ];

    'account/from-id': [[select_account_from_id], accounts];

    'account/all': [[select_account_all], accounts];

    'account/request-email-change': [
        [update_account_request_email_change],
        unknown,
    ];

    'account/change-username': [[update_account_change_username], unknown];

    'account/roles': [
        [
            {
                id: string;
            },
        ],
        roles,
    ];

    'db/get-version': [[select_db_get_version], version];

    'db/change-version': [[update_db_change_version], unknown];

    'db/init': [[insert_db_init], unknown];
};
