// This file was generated by a script, please do not modify it. If you see any problems, please raise an issue on https://github.com/tsaxking/webpack-template/issues

import { Accounts } from './tables-1.ts';
import { Members } from './tables-1.ts';
import { Roles } from './tables-1.ts';
import { AccountRoles } from './tables-1.ts';
import { Permissions } from './tables-1.ts';
import { Version } from './tables-1.ts';
import { Sessions } from './tables-1.ts';
import { AccountSettings } from './tables-1.ts';
import { Select_roles_from_id } from './tables-1.ts';
import { Select_roles_from_name } from './tables-1.ts';
import { Insert_roles_new } from './tables-1.ts';
import { Delete_roles_delete } from './tables-1.ts';
import { Update_roles_update } from './tables-1.ts';
import { Select_roles_all } from './tables-1.ts';
import { Insert_sessions_new } from './tables-1.ts';
import { Delete_sessions_delete } from './tables-1.ts';
import { Update_sessions_update } from './tables-1.ts';
import { Select_sessions_get } from './tables-1.ts';
import { Delete_sessions_delete_all } from './tables-1.ts';
import { Select_sessions_all } from './tables-1.ts';
import { Select_account_from_verification_key } from './tables-1.ts';
import { Update_account_change_email } from './tables-1.ts';
import { Select_account_verified } from './tables-1.ts';
import { Select_account_get_settings } from './tables-1.ts';
import { Select_account_from_id } from './tables-1.ts';
import { Update_account_unverify } from './tables-1.ts';
import { Insert_account_add_role } from './tables-1.ts';
import { Update_account_update_picture } from './tables-1.ts';
import { Insert_account_new } from './tables-1.ts';
import { Update_account_verify } from './tables-1.ts';
import { Delete_account_delete } from './tables-1.ts';
import { Update_account_change_username } from './tables-1.ts';
import { Delete_account_remove_role } from './tables-1.ts';
import { Update_account_request_email_change } from './tables-1.ts';
import { Select_account_from_username } from './tables-1.ts';
import { Update_account_set_verification } from './tables-1.ts';
import { Update_account_change_password } from './tables-1.ts';
import { Insert_account_save_settings } from './tables-1.ts';
import { Select_account_from_email } from './tables-1.ts';
import { Select_account_all } from './tables-1.ts';
import { Select_account_from_password_change } from './tables-1.ts';
import { Update_account_request_password_change } from './tables-1.ts';
import { Select_account_unverified } from './tables-1.ts';
import { Select_db_get_version } from './tables-1.ts';
import { Insert_db_init } from './tables-1.ts';
import { Update_db_change_version } from './tables-1.ts';
import { Select_permissions_all } from './tables-1.ts';
import { Update_member_update_bio } from './tables-1.ts';
import { Update_member_add_to_board } from './tables-1.ts';
import { Update_member_remove_from_board } from './tables-1.ts';
import { Insert_member_new } from './tables-1.ts';
import { Delete_member_delete } from './tables-1.ts';
import { Update_member_update_status } from './tables-1.ts';
import { Select_member_all } from './tables-1.ts';
import { Update_member_update_resume } from './tables-1.ts';
import { Update_member_update_title } from './tables-1.ts';


export type Queries = {

            'roles/from-id': [
                [
                    Select_roles_from_id
                ],
                Roles
            ];
        
            'roles/from-name': [
                [
                    Select_roles_from_name
                ],
                Roles
            ];
        
            'roles/new': [
                [
                    Insert_roles_new
                ],
                unknown
            ];
        
            'roles/delete': [
                [
                    Delete_roles_delete
                ],
                unknown
            ];
        
            'roles/update': [
                [
                    Update_roles_update
                ],
                unknown
            ];
        
            'roles/all': [
                [
                    Select_roles_all
                ],
                Roles
            ];
        
            'sessions/new': [
                [
                    Insert_sessions_new
                ],
                unknown
            ];
        
            'sessions/delete': [
                [
                    Delete_sessions_delete
                ],
                unknown
            ];
        
            'sessions/update': [
                [
                    Update_sessions_update
                ],
                unknown
            ];
        
            'sessions/get': [
                [
                    Select_sessions_get
                ],
                Sessions
            ];
        
            'sessions/delete-all': [
                [
                    Delete_sessions_delete_all
                ],
                unknown
            ];
        
            'sessions/all': [
                [
                    Select_sessions_all
                ],
                Sessions
            ];
        
            'account/from-verification-key': [
                [
                    Select_account_from_verification_key
                ],
                Accounts
            ];
        
            'account/change-email': [
                [
                    Update_account_change_email
                ],
                unknown
            ];
        
            'account/verified': [
                [
                    Select_account_verified
                ],
                Accounts
            ];
        
            'account/get-settings': [
                [
                    Select_account_get_settings
                ],
                AccountSettings
            ];
        
            'account/from-id': [
                [
                    Select_account_from_id
                ],
                Accounts
            ];
        
            'account/unverify': [
                [
                    Update_account_unverify
                ],
                unknown
            ];
        
            'account/add-role': [
                [
                    Insert_account_add_role
                ],
                unknown
            ];
        
            'account/update-picture': [
                [
                    Update_account_update_picture
                ],
                unknown
            ];
        
            'account/new': [
                [
                    Insert_account_new
                ],
                unknown
            ];
        
            'account/verify': [
                [
                    Update_account_verify
                ],
                unknown
            ];
        
            'account/delete': [
                [
                    Delete_account_delete
                ],
                unknown
            ];
        
            'account/change-username': [
                [
                    Update_account_change_username
                ],
                unknown
            ];
        
            'account/remove-role': [
                [
                    Delete_account_remove_role
                ],
                unknown
            ];
        
            'account/request-email-change': [
                [
                    Update_account_request_email_change
                ],
                unknown
            ];
        
            'account/from-username': [
                [
                    Select_account_from_username
                ],
                Accounts
            ];
        
            'account/set-verification': [
                [
                    Update_account_set_verification
                ],
                unknown
            ];
        
            'account/change-password': [
                [
                    Update_account_change_password
                ],
                unknown
            ];
        
            'account/save-settings': [
                [
                    Insert_account_save_settings
                ],
                unknown
            ];
        
            'account/from-email': [
                [
                    Select_account_from_email
                ],
                Accounts
            ];
        
            'account/all': [
                [
                    Select_account_all
                ],
                Accounts
            ];
        
            'account/from-password-change': [
                [
                    Select_account_from_password_change
                ],
                Accounts
            ];
        
            'account/request-password-change': [
                [
                    Update_account_request_password_change
                ],
                unknown
            ];
        
            'account/unverified': [
                [
                    Select_account_unverified
                ],
                Accounts
            ];
        
            'db/get-version': [
                [
                    Select_db_get_version
                ],
                Version
            ];
        
            'db/init': [
                [
                    Insert_db_init
                ],
                unknown
            ];
        
            'db/change-version': [
                [
                    Update_db_change_version
                ],
                unknown
            ];
        
            'permissions/all': [
                [
                    Select_permissions_all
                ],
                Permissions
            ];
        
            'member/update-bio': [
                [
                    Update_member_update_bio
                ],
                unknown
            ];
        
            'member/add-to-board': [
                [
                    Update_member_add_to_board
                ],
                unknown
            ];
        
            'member/remove-from-board': [
                [
                    Update_member_remove_from_board
                ],
                unknown
            ];
        
            'member/new': [
                [
                    Insert_member_new
                ],
                unknown
            ];
        
            'member/delete': [
                [
                    Delete_member_delete
                ],
                unknown
            ];
        
            'member/update-status': [
                [
                    Update_member_update_status
                ],
                unknown
            ];
        
            'member/all': [
                [
                    Select_member_all
                ],
                Members
            ];
        
            'member/update-resume': [
                [
                    Update_member_update_resume
                ],
                unknown
            ];
        
            'member/update-title': [
                [
                    Update_member_update_title
                ],
                unknown
            ];
        
};