// This file was generated by a script, please do not modify it. If you see any issues, please raise an issue on https://github.com/tsaxking/webpack-template/issues

export type Accounts = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Members = {
    id: string;
    title: string | null;
    status: string | null;
    bio: string | null;
    resume: string | null;
    board: number;
};

export type Roles = {
    id: string;
    name: string;
    description: string | null;
    rank: number;
};

export type AccountRoles = {
    accountId: string;
    roleId: string;
};

export type Permissions = {
    roleId: string;
    permission: string;
};

export type Version = {
    major: string | null;
    minor: string | null;
    patch: string | null;
};

export type Sessions = {
    id: string;
    accountId: string | null;
    ip: string | null;
    userAgent: string | null;
    latestActivity: string | null;
    requests: number;
    created: number;
    prevUrl: string | null;
};

export type AccountSettings = {
    accountId: string;
    settings: string;
};









export type Select_storage_db_queries_permissions_all = Record<string, unknown>;export type Return_storage_db_queries_permissions_all = {
    roleId: string;
    permission: string;
};

export type Select_storage_db_queries_roles_from_name = {
    name: string;
};export type Return_storage_db_queries_roles_from_name = {
    id: string;
    name: string;
    description: string | null;
    rank: number;
};

export type Delete_storage_db_queries_roles_delete = {
    id: string;
};

export type Update_storage_db_queries_roles_update = {
    name: string;
    description: string | null;
    rank: number;
    id: string;
};

export type Insert_storage_db_queries_roles_new = {
    id: string;
    name: string;
    description: string | null;
    rank: number;
};

export type Select_storage_db_queries_roles_from_id = {
    id: string;
};export type Return_storage_db_queries_roles_from_id = {
    id: string;
    name: string;
    description: string | null;
    rank: number;
};

export type Select_storage_db_queries_roles_all = Record<string, unknown>;export type Return_storage_db_queries_roles_all = {
    id: string;
    name: string;
    description: string | null;
    rank: number;
};

export type Delete_storage_db_queries_sessions_delete = {
    id: string;
};





export type Delete_storage_db_queries_sessions_delete_all = Record<string, unknown>;

export type Update_storage_db_queries_sessions_update = {
    accountId: string | null;
    userAgent: string | null;
    latestActivity: string | null;
    requests: number;
    ip: string | null;
    prevUrl: string | null;
    id: string;
};

export type Insert_storage_db_queries_sessions_new = {
    id: string;
    accountId: string | null;
    userAgent: string | null;
    latestActivity: string | null;
    requests: number;
    created: number;
    ip: string | null;
    prevUrl: string | null;
};

export type Select_storage_db_queries_sessions_get = {
    id: string;
};export type Return_storage_db_queries_sessions_get = {
    id: string;
    accountId: string | null;
    ip: string | null;
    userAgent: string | null;
    latestActivity: string | null;
    requests: number;
    created: number;
    prevUrl: string | null;
};

export type Select_storage_db_queries_sessions_all = Record<string, unknown>;export type Return_storage_db_queries_sessions_all = {
    id: string;
    accountId: string | null;
    ip: string | null;
    userAgent: string | null;
    latestActivity: string | null;
    requests: number;
    created: number;
    prevUrl: string | null;
};



export type Delete_storage_db_queries_member_delete = {
    id: string;
};



export type Update_storage_db_queries_member_update_title = {
    title: string | null;
    id: string;
};



export type Update_storage_db_queries_member_update_status = {
    id: string;
};

export type Update_storage_db_queries_member_update_resume = {
    id: string;
};



export type Update_storage_db_queries_member_remove_from_board = {
    id: string;
};



export type Insert_storage_db_queries_member_new = {
    id: string;
    "status": undefined;
};

export type Update_storage_db_queries_member_update_bio = {
    bio: string | null;
    id: string;
};

export type Update_storage_db_queries_member_add_to_board = {
    id: string;
};

export type Select_storage_db_queries_member_all = Record<string, unknown>;export type Return_storage_db_queries_member_all = {
    id: string;
    title: string | null;
    status: string | null;
    bio: string | null;
    resume: string | null;
    board: number;
};

export type Update_storage_db_queries_account_unverify = {
    id: string;
};

export type Update_storage_db_queries_account_set_verification = {
    verification: string | null;
    id: string;
};



export type Delete_storage_db_queries_account_delete = {
    id: string;
};

export type Select_storage_db_queries_account_unverified = Record<string, unknown>;export type Return_storage_db_queries_account_unverified = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Update_storage_db_queries_account_change_password = {
    salt: string;
    passwordChange: string | null;
    id: string;
};

export type Insert_storage_db_queries_account_save_settings = {
    accountId: string;
    settings: string;
};

export type Select_storage_db_queries_account_from_username = {
    username: string;
};export type Return_storage_db_queries_account_from_username = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Update_storage_db_queries_account_update_picture = {
    picture: string | null;
    id: string;
};

export type Select_storage_db_queries_account_from_verification_key = {
    verification: string | null;
};export type Return_storage_db_queries_account_from_verification_key = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Select_storage_db_queries_account_verified = Record<string, unknown>;export type Return_storage_db_queries_account_verified = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Update_storage_db_queries_account_verify = {
    id: string;
};

export type Select_storage_db_queries_account_get_settings = {
    accountId: string;
};export type Return_storage_db_queries_account_get_settings = {
    accountId: string;
    settings: string;
};

export type Update_storage_db_queries_account_change_email = {
    email: string;
    id: string;
};

export type Delete_storage_db_queries_account_remove_role = {
    accountId: string;
    roleId: string;
};

export type Insert_storage_db_queries_account_add_role = {
    accountId: string;
    roleId: string;
};

export type Select_storage_db_queries_account_from_email = {
    email: string;
};export type Return_storage_db_queries_account_from_email = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Insert_storage_db_queries_account_new = {
    id: string;
    username: string;
    "key": undefined;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    verified: number;
    verification: string | null;
    created: string;
    phoneNumber: string | null;
};

export type Update_storage_db_queries_account_request_password_change = {
    passwordChange: string | null;
    id: string;
};

export type Select_storage_db_queries_account_from_password_change = {
    passwordChange: string | null;
};export type Return_storage_db_queries_account_from_password_change = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Select_storage_db_queries_account_from_id = {
    id: string;
};export type Return_storage_db_queries_account_from_id = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Select_storage_db_queries_account_all = Record<string, unknown>;export type Return_storage_db_queries_account_all = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | null;
    picture: string | null;
    verified: number;
    verification: string | null;
    emailChange: string | null;
    passwordChangeDate: string | null;
    phoneNumber: string | null;
    created: string;
};

export type Update_storage_db_queries_account_request_email_change = {
    emailChange: string | null;
    id: string;
};

export type Update_storage_db_queries_account_change_username = {
    username: string;
    id: string;
};

export type Select_storage_db_queries_db_get_version = Record<string, unknown>;export type Return_storage_db_queries_db_get_version = {
    major: string | null;
    minor: string | null;
    patch: string | null;
};

export type Update_storage_db_queries_db_change_version = {
    version: undefined;
};









