export type SocketEvent = 
      'disconnect'
	| 'account:created'
	| 'account:logged-in'
	| 'account:logged-out'
	| 'account:removed'
	| 'account:unverified'
	| 'account:update-email'
	| 'account:update-first-name'
	| 'account:update-last-name'
	| 'account:update-phone-number'
	| 'account:update-picture'
	| 'account:update-username'
	| 'account:verified'
	| 'member:add-skill'
	| 'member:remove-skill'
	| 'member:request'
	| 'member:update-bio'
	| 'member:update-resume'
	| 'member:update-title'
	| 'page:open'
	| 'roles:added'
	| 'roles:removed'
	| 'skills:added'
	| 'skills:removed'
;