name: Lint

on: workflow_call

permissions:
    contents: read

concurrency:
  group: 'checks'
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve git dependencies
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v20.4

      - name: Run
        run: |
          echo "Installing dependencies..."
          npm i
          echo "Running linter..."
          npm run lint
  